# Side Information 번역
구글 번역 API 사용

In [1]:
# !pip install googletrans==4.0.0-rc1
import googletrans
import pandas as pd
from tqdm import tqdm
import numpy as np
import pickle
import time

In [2]:
# ⬇️ 간단한 사용법
# -------------------------------------------------

# translator = googletrans.Translator()

# aaa = 'Hi, my name is chaeminsu'

# out = translator.translate(aaa,dest='ko', src='en')
# print(out.text)
# >>> 안녕하세요, 제 이름은 Chaeminsu입니다

In [3]:
df_3229 = pd.read_csv('/opt/ml/input/final_project/MBTI_merge_movieLens_3229_movie.csv')
side_info_df = pd.read_csv('/opt/ml/input/final_project/Crawling/imdb_side_df_EmptyList_to_None.csv')

In [4]:
df_3229_plus_side_info = pd.merge(df_3229,side_info_df, how='left', on='Contents')
df_3229_plus_side_info

,Character,Contents,Votes,MBTI,Enneagram,category,img_src,Page,title,movieId,searched_content,genres,plot,directors,actors,produceers,composers
0,Moana Waialiki,Moana (2016),2.7k/477,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,moana,73141.0,Moana,"['Animation', 'Adventure', 'Comedy', 'Family',...","[""In Ancient Polynesia, when a terrible curse ...","['Ron Clements', 'John Musker', 'Don Hall', 'C...","[""Auli'i Cravalho"", 'Dwayne Johnson', 'Rachel ...",NaN,NaN
1,Joy,Inside Out (2015),2.5k/358,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,inside out,122470.0,Inside Out,"['Animation', 'Adventure', 'Comedy', 'Drama', ...",['After young Riley is uprooted from her Midwe...,"['Pete Docter', 'Ronnie Del Carmen']","['Amy Poehler', 'Phyllis Smith', 'Richard Kind...",NaN,NaN
2,Judy Hopps,Zootopia (2016),2.3k/350,ENFJ,1w2,movies,https://static1.personality-database.com/profi...,1,zootopia,152081.0,Zootopia,"['Animation', 'Adventure', 'Comedy', 'Crime', ...","['In a city of anthropomorphic animals, a rook...","['Byron Howard', 'Rich Moore', 'Jared Bush']","['Ginnifer Goodwin', 'Jason Bateman', 'Idris E...",NaN,NaN
3,Elle Woods,Legally Blonde (2001),1.9k/227,ENFJ,3w2,movies,https://static1.personality-database.com/profi...,1,legally blonde,4447.0,Legally Blonde,"['Comedy', 'Romance']",NaN,['Robert Luketic'],"['Reese Witherspoon', 'Luke Wilson', 'Selma Bl...",NaN,NaN
4,Neil Perry,Dead Poets Society (1989),1.7k/222,ENFJ,4w3,movies,https://static1.personality-database.com/profi...,1,dead poets society,1246.0,Dead Poets Society,"['Comedy', 'Drama']",['Maverick teacher John Keating uses poetry to...,['Peter Weir'],"['Robin Williams', 'Robert Sean Leonard', 'Eth...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15990,Diana Reiter,Schindler's List (1993),6/0,INFJ,5w6,movies,https://static1.personality-database.com/profi...,210,schindler's list,527.0,Schindler's List,"['Biography', 'Drama', 'History']",['In German-occupied Poland during World War I...,['Steven Spielberg'],"['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes...",NaN,NaN
15991,Berkeley Cole,Out of Africa (1985),6/0,INFJ,1w9,movies,https://static1.personality-database.com/profi...,210,out of africa,1959.0,Out of Africa,"['Biography', 'Drama', 'Romance']","['In 20th-century colonial Kenya, a Danish bar...",['Sydney Pollack'],"['Meryl Streep', 'Robert Redford', 'Klaus Mari...",NaN,NaN
15992,The Girl,A Girl Walks Home Alone at Night (2014),6/0,INFJ,4w5,movies,https://static1.personality-database.com/profi...,210,a girl walks home alone at night,118880.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15993,Urzah,The Dark Crystal (1982),6/0,INFJ,9w1,movies,https://static1.personality-database.com/profi...,210,the dark crystal,91077.0,The Dark Crystal,"['Adventure', 'Family', 'Fantasy']",NaN,"['Jim Henson', 'Frank Oz']","['Jim Henson', 'Kathryn Mullen', 'Frank Oz', '...",NaN,NaN
15994,Dr. Leonora Orantes,Contagion (2011),6/0,INFJ,9w1,movies,https://static1.personality-database.com/profi...,210,contagion,89470.0,Contagion,"['Drama', 'Thriller']","['Healthcare professionals, government officia...",['Steven Soderbergh'],"['Gwyneth Paltrow', 'Tien You Chui', 'Josie Ho...",NaN,NaN

In [5]:
translator = googletrans.Translator()

# def trans_to_ko(s):
#     out = translator.translate(s,dest='ko', src='en')
#     return out.text

def trans_to_ko(s):
    if s and isinstance(s, str):
        out = translator.translate(s,dest='ko', src='en')
        time.sleep(0.3)
        return out.text
    else:
        return None

In [6]:
df_fillna_no_du = df_3229_plus_side_info.drop_duplicates(subset='movieId')
df_fillna_no_du = df_fillna_no_du.drop(['produceers', 'composers'], axis=1)
df_fillna_no_du

,Character,Contents,Votes,MBTI,Enneagram,category,img_src,Page,title,movieId,searched_content,genres,plot,directors,actors
0,Moana Waialiki,Moana (2016),2.7k/477,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,moana,73141.0,Moana,"['Animation', 'Adventure', 'Comedy', 'Family',...","[""In Ancient Polynesia, when a terrible curse ...","['Ron Clements', 'John Musker', 'Don Hall', 'C...","[""Auli'i Cravalho"", 'Dwayne Johnson', 'Rachel ..."
1,Joy,Inside Out (2015),2.5k/358,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,inside out,122470.0,Inside Out,"['Animation', 'Adventure', 'Comedy', 'Drama', ...",['After young Riley is uprooted from her Midwe...,"['Pete Docter', 'Ronnie Del Carmen']","['Amy Poehler', 'Phyllis Smith', 'Richard Kind..."
2,Judy Hopps,Zootopia (2016),2.3k/350,ENFJ,1w2,movies,https://static1.personality-database.com/profi...,1,zootopia,152081.0,Zootopia,"['Animation', 'Adventure', 'Comedy', 'Crime', ...","['In a city of anthropomorphic animals, a rook...","['Byron Howard', 'Rich Moore', 'Jared Bush']","['Ginnifer Goodwin', 'Jason Bateman', 'Idris E..."
3,Elle Woods,Legally Blonde (2001),1.9k/227,ENFJ,3w2,movies,https://static1.personality-database.com/profi...,1,legally blonde,4447.0,Legally Blonde,"['Comedy', 'Romance']",NaN,['Robert Luketic'],"['Reese Witherspoon', 'Luke Wilson', 'Selma Bl..."
4,Neil Perry,Dead Poets Society (1989),1.7k/222,ENFJ,4w3,movies,https://static1.personality-database.com/profi...,1,dead poets society,1246.0,Dead Poets Society,"['Comedy', 'Drama']",['Maverick teacher John Keating uses poetry to...,['Peter Weir'],"['Robin Williams', 'Robert Sean Leonard', 'Eth..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15977,Sasha,Cube²: Hypercube (2002),7/0,INFJ,5w6,movies,https://static1.personality-database.com/profi...,206,cube²: hypercube,27482.0,NaN,NaN,NaN,NaN,NaN
15978,Karel Kopfrkingl,The Cremator (Spalovač mrtvol) 1969,7/0,INFJ,1w9,movies,https://static1.personality-database.com/profi...,207,the cremator,76208.0,NaN,NaN,NaN,NaN,NaN
15979,Robert Bilott,Dark Waters (2019),7/1,INFJ,3w2,movies,https://static1.personality-database.com/profi...,207,dark waters,177115.0,Dark Waters,"['Biography', 'Drama', 'History']",['A corporate defense attorney takes on an env...,['Todd Haynes'],"['Mark Ruffalo', 'Anne Hathaway', 'Tim Robbins..."
15989,Prince Albert of Saxe-Coburg and Gotha,The Young Victoria (2009),6/0,INFJ,XwX,movies,https://pdb-web-static.s3.us-east-2.amazonaws....,210,the young victoria,68269.0,The Young Victoria,"['Biography', 'Drama', 'History', 'Romance']","[""A dramatization of the turbulent first years...",['Jean-Marc Vallée'],"['Emily Blunt', 'Rupert Friend', 'Paul Bettany..."
15992,The Girl,A Girl Walks Home Alone at Night (2014),6/0,INFJ,4w5,movies,https://static1.personality-database.com/profi...,210,a girl walks home alone at night,118880.0,NaN,NaN,NaN,NaN,NaN

In [7]:
df_fillna_no_du

,Character,Contents,Votes,MBTI,Enneagram,category,img_src,Page,title,movieId,searched_content,genres,plot,directors,actors
0,Moana Waialiki,Moana (2016),2.7k/477,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,moana,73141.0,Moana,"['Animation', 'Adventure', 'Comedy', 'Family',...","[""In Ancient Polynesia, when a terrible curse ...","['Ron Clements', 'John Musker', 'Don Hall', 'C...","[""Auli'i Cravalho"", 'Dwayne Johnson', 'Rachel ..."
1,Joy,Inside Out (2015),2.5k/358,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,inside out,122470.0,Inside Out,"['Animation', 'Adventure', 'Comedy', 'Drama', ...",['After young Riley is uprooted from her Midwe...,"['Pete Docter', 'Ronnie Del Carmen']","['Amy Poehler', 'Phyllis Smith', 'Richard Kind..."
2,Judy Hopps,Zootopia (2016),2.3k/350,ENFJ,1w2,movies,https://static1.personality-database.com/profi...,1,zootopia,152081.0,Zootopia,"['Animation', 'Adventure', 'Comedy', 'Crime', ...","['In a city of anthropomorphic animals, a rook...","['Byron Howard', 'Rich Moore', 'Jared Bush']","['Ginnifer Goodwin', 'Jason Bateman', 'Idris E..."
3,Elle Woods,Legally Blonde (2001),1.9k/227,ENFJ,3w2,movies,https://static1.personality-database.com/profi...,1,legally blonde,4447.0,Legally Blonde,"['Comedy', 'Romance']",NaN,['Robert Luketic'],"['Reese Witherspoon', 'Luke Wilson', 'Selma Bl..."
4,Neil Perry,Dead Poets Society (1989),1.7k/222,ENFJ,4w3,movies,https://static1.personality-database.com/profi...,1,dead poets society,1246.0,Dead Poets Society,"['Comedy', 'Drama']",['Maverick teacher John Keating uses poetry to...,['Peter Weir'],"['Robin Williams', 'Robert Sean Leonard', 'Eth..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15977,Sasha,Cube²: Hypercube (2002),7/0,INFJ,5w6,movies,https://static1.personality-database.com/profi...,206,cube²: hypercube,27482.0,NaN,NaN,NaN,NaN,NaN
15978,Karel Kopfrkingl,The Cremator (Spalovač mrtvol) 1969,7/0,INFJ,1w9,movies,https://static1.personality-database.com/profi...,207,the cremator,76208.0,NaN,NaN,NaN,NaN,NaN
15979,Robert Bilott,Dark Waters (2019),7/1,INFJ,3w2,movies,https://static1.personality-database.com/profi...,207,dark waters,177115.0,Dark Waters,"['Biography', 'Drama', 'History']",['A corporate defense attorney takes on an env...,['Todd Haynes'],"['Mark Ruffalo', 'Anne Hathaway', 'Tim Robbins..."
15989,Prince Albert of Saxe-Coburg and Gotha,The Young Victoria (2009),6/0,INFJ,XwX,movies,https://pdb-web-static.s3.us-east-2.amazonaws....,210,the young victoria,68269.0,The Young Victoria,"['Biography', 'Drama', 'History', 'Romance']","[""A dramatization of the turbulent first years...",['Jean-Marc Vallée'],"['Emily Blunt', 'Rupert Friend', 'Paul Bettany..."
15992,The Girl,A Girl Walks Home Alone at Night (2014),6/0,INFJ,4w5,movies,https://static1.personality-database.com/profi...,210,a girl walks home alone at night,118880.0,NaN,NaN,NaN,NaN,NaN

In [8]:
ko_dict = {'movieId':[], 'ko_genres':[], 'ko_plot':[]}

In [27]:
for mid, g, p in tqdm(zip(df_fillna_no_du['movieId'][3203:], df_fillna_no_du['genres'][3203:], df_fillna_no_du['plot'][3203:])):
    try:
        g = trans_to_ko(g)
        g = g[2:-3]
    except TypeError:
        g = '장르 정보 없음'
    try:
        p = trans_to_ko(p)
        p = p[3:-3]
    except TypeError:
        p = '줄거리 정보 없음'
    ko_dict['movieId'].append(mid)
    ko_dict['ko_genres'].append(g)
    ko_dict['ko_plot'].append(p)

26it [00:37,  1.42s/it]

In [28]:
print(len(ko_dict['movieId']))
print(len(ko_dict['ko_genres']))
print(len(ko_dict['ko_plot']))

3229
3229
3229

In [32]:
ko_genres_plot_3229_df = pd.DataFrame(ko_dict)
ko_genres_plot_3229_df

,movieId,ko_genres,ko_plot
0,73141.0,"'애니메이션', '어드벤처', '코미디', '가족', '판타지', '뮤지컬'","고대 폴리네시아에서, 반신 마우이가 발생한 끔찍한 저주가 모아 나 섬에 도착했을 때..."
1,122470.0,"'애니메이션', '어드벤처', '코미디', '드라마', '가족', '판타지'","젊은 라일리가 중서부 생활에서 뿌리를 내리고 샌프란시스코로 이사 한 후, 그녀의 감..."
2,152081.0,"'애니메이션', '어드벤처', '코미디', '범죄', '가족', '미스터리'",의인화 동물 도시에서 신인 토끼 경찰과 냉소적 인 사기 아티스트 폭스는 음모를 밝히...
3,4447.0,"'코미디', '로맨",줄거리 정보 없음
4,1246.0,"'코미디', '드라",매버릭 교사 인 존 키팅 (John Keating)은시를 사용하여 그의 기숙 학교 ...
...,...,...,...
3224,27482.0,장르 정보 없음,줄거리 정보 없음
3225,76208.0,장르 정보 없음,줄거리 정보 없음
3226,177115.0,"'전기', '드라마', '역",기업 변호사 변호사는 오랫동안 오염의 역사를 드러내는 화학 회사에 대한 환경 소송을...
3227,68269.0,"'전기', '드라마', '역사', '로맨스'","빅토리아 여왕의 통치의 첫해와 앨버트 왕자와의 지속적인 로맨스의 드라마화.""그녀의 ..."
3228,118880.0,장르 정보 없음,줄거리 정보 없음

In [33]:
ko_genres_plot_3229_df.to_csv('/opt/ml/input/final_project/Data/Crawling/ko_genres_plot_3229_df.csv')

In [34]:
ko_3229_merge_df = pd.merge(df_3229_plus_side_info,ko_genres_plot_3229_df, how='left', on='movieId')
ko_3229_merge_df

,Character,Contents,Votes,MBTI,Enneagram,category,img_src,Page,title,movieId,searched_content,genres,plot,directors,actors,produceers,composers,ko_genres,ko_plot
0,Moana Waialiki,Moana (2016),2.7k/477,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,moana,73141.0,Moana,"['Animation', 'Adventure', 'Comedy', 'Family',...","[""In Ancient Polynesia, when a terrible curse ...","['Ron Clements', 'John Musker', 'Don Hall', 'C...","[""Auli'i Cravalho"", 'Dwayne Johnson', 'Rachel ...",NaN,NaN,"'애니메이션', '어드벤처', '코미디', '가족', '판타지', '뮤지컬'","고대 폴리네시아에서, 반신 마우이가 발생한 끔찍한 저주가 모아 나 섬에 도착했을 때..."
1,Joy,Inside Out (2015),2.5k/358,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,inside out,122470.0,Inside Out,"['Animation', 'Adventure', 'Comedy', 'Drama', ...",['After young Riley is uprooted from her Midwe...,"['Pete Docter', 'Ronnie Del Carmen']","['Amy Poehler', 'Phyllis Smith', 'Richard Kind...",NaN,NaN,"'애니메이션', '어드벤처', '코미디', '드라마', '가족', '판타지'","젊은 라일리가 중서부 생활에서 뿌리를 내리고 샌프란시스코로 이사 한 후, 그녀의 감..."
2,Judy Hopps,Zootopia (2016),2.3k/350,ENFJ,1w2,movies,https://static1.personality-database.com/profi...,1,zootopia,152081.0,Zootopia,"['Animation', 'Adventure', 'Comedy', 'Crime', ...","['In a city of anthropomorphic animals, a rook...","['Byron Howard', 'Rich Moore', 'Jared Bush']","['Ginnifer Goodwin', 'Jason Bateman', 'Idris E...",NaN,NaN,"'애니메이션', '어드벤처', '코미디', '범죄', '가족', '미스터리'",의인화 동물 도시에서 신인 토끼 경찰과 냉소적 인 사기 아티스트 폭스는 음모를 밝히...
3,Elle Woods,Legally Blonde (2001),1.9k/227,ENFJ,3w2,movies,https://static1.personality-database.com/profi...,1,legally blonde,4447.0,Legally Blonde,"['Comedy', 'Romance']",NaN,['Robert Luketic'],"['Reese Witherspoon', 'Luke Wilson', 'Selma Bl...",NaN,NaN,"'코미디', '로맨",줄거리 정보 없음
4,Neil Perry,Dead Poets Society (1989),1.7k/222,ENFJ,4w3,movies,https://static1.personality-database.com/profi...,1,dead poets society,1246.0,Dead Poets Society,"['Comedy', 'Drama']",['Maverick teacher John Keating uses poetry to...,['Peter Weir'],"['Robin Williams', 'Robert Sean Leonard', 'Eth...",NaN,NaN,"'코미디', '드라",매버릭 교사 인 존 키팅 (John Keating)은시를 사용하여 그의 기숙 학교 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15990,Diana Reiter,Schindler's List (1993),6/0,INFJ,5w6,movies,https://static1.personality-database.com/profi...,210,schindler's list,527.0,Schindler's List,"['Biography', 'Drama', 'History']",['In German-occupied Poland during World War I...,['Steven Spielberg'],"['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes...",NaN,NaN,"'전기', '드라마', '역",제 2 차 세계 대전 당시 독일 점령 폴란드에서 산업 주의자 Oskar Schind...
15991,Berkeley Cole,Out of Africa (1985),6/0,INFJ,1w9,movies,https://static1.personality-database.com/profi...,210,out of africa,1959.0,Out of Africa,"['Biography', 'Drama', 'Romance']","['In 20th-century colonial Kenya, a Danish bar...",['Sydney Pollack'],"['Meryl Streep', 'Robert Redford', 'Klaus Mari...",NaN,NaN,"'전기', '드라마', '로맨",20 세기 식민지 케냐에서 덴마크의 남작/농장 소유자는 자유로운 큰 빅 게임 헌터와...
15992,The Girl,A Girl Walks Home Alone at Night (2014),6/0,INFJ,4w5,movies,https://static1.personality-database.com/profi...,210,a girl walks home alone at night,118880.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,장르 정보 없음,줄거리 정보 없음
15993,Urzah,The Dark Crystal (1982),6/0,INFJ,9w1,movies,https://static1.personality-database.com/profi...,210,the dark crystal,91077.0,The Dark Crystal,"['Adventure', 'Family', 'Fantasy']",NaN,"['Jim Henson', 'Frank Oz']","['Jim Henson', 'Kathryn Mullen', 'Frank Oz', '...",NaN,NaN,"'Adventure', 'Family', 'Fantas",줄거리 정보 없음
15994,Dr. Leonora Orantes,Contagion (2011),6/0,INFJ,9w1,movies,https://static1.personality-database.com/profi...,210,contagion,89470.0,Contagion,"['Drama', 'Thriller']","['Healthcare professionals, government officia...",['Steven Soderbergh'],"['Gwyneth Paltrow', 'Tien You Chui', 'Josie Ho...",NaN,NaN,"'드라마', '스릴","의료 전문가, 공무원 및 일상적인 사람들은 CDC가 치료법을 찾기 위해 일할 때 전..."

In [35]:
ko_3229_merge_df = ko_3229_merge_df.drop(['produceers','composers'],axis=1)
ko_3229_merge_df

,Character,Contents,Votes,MBTI,Enneagram,category,img_src,Page,title,movieId,searched_content,genres,plot,directors,actors,ko_genres,ko_plot
0,Moana Waialiki,Moana (2016),2.7k/477,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,moana,73141.0,Moana,"['Animation', 'Adventure', 'Comedy', 'Family',...","[""In Ancient Polynesia, when a terrible curse ...","['Ron Clements', 'John Musker', 'Don Hall', 'C...","[""Auli'i Cravalho"", 'Dwayne Johnson', 'Rachel ...","'애니메이션', '어드벤처', '코미디', '가족', '판타지', '뮤지컬'","고대 폴리네시아에서, 반신 마우이가 발생한 끔찍한 저주가 모아 나 섬에 도착했을 때..."
1,Joy,Inside Out (2015),2.5k/358,ENFJ,7w6,movies,https://static1.personality-database.com/profi...,1,inside out,122470.0,Inside Out,"['Animation', 'Adventure', 'Comedy', 'Drama', ...",['After young Riley is uprooted from her Midwe...,"['Pete Docter', 'Ronnie Del Carmen']","['Amy Poehler', 'Phyllis Smith', 'Richard Kind...","'애니메이션', '어드벤처', '코미디', '드라마', '가족', '판타지'","젊은 라일리가 중서부 생활에서 뿌리를 내리고 샌프란시스코로 이사 한 후, 그녀의 감..."
2,Judy Hopps,Zootopia (2016),2.3k/350,ENFJ,1w2,movies,https://static1.personality-database.com/profi...,1,zootopia,152081.0,Zootopia,"['Animation', 'Adventure', 'Comedy', 'Crime', ...","['In a city of anthropomorphic animals, a rook...","['Byron Howard', 'Rich Moore', 'Jared Bush']","['Ginnifer Goodwin', 'Jason Bateman', 'Idris E...","'애니메이션', '어드벤처', '코미디', '범죄', '가족', '미스터리'",의인화 동물 도시에서 신인 토끼 경찰과 냉소적 인 사기 아티스트 폭스는 음모를 밝히...
3,Elle Woods,Legally Blonde (2001),1.9k/227,ENFJ,3w2,movies,https://static1.personality-database.com/profi...,1,legally blonde,4447.0,Legally Blonde,"['Comedy', 'Romance']",NaN,['Robert Luketic'],"['Reese Witherspoon', 'Luke Wilson', 'Selma Bl...","'코미디', '로맨",줄거리 정보 없음
4,Neil Perry,Dead Poets Society (1989),1.7k/222,ENFJ,4w3,movies,https://static1.personality-database.com/profi...,1,dead poets society,1246.0,Dead Poets Society,"['Comedy', 'Drama']",['Maverick teacher John Keating uses poetry to...,['Peter Weir'],"['Robin Williams', 'Robert Sean Leonard', 'Eth...","'코미디', '드라",매버릭 교사 인 존 키팅 (John Keating)은시를 사용하여 그의 기숙 학교 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15990,Diana Reiter,Schindler's List (1993),6/0,INFJ,5w6,movies,https://static1.personality-database.com/profi...,210,schindler's list,527.0,Schindler's List,"['Biography', 'Drama', 'History']",['In German-occupied Poland during World War I...,['Steven Spielberg'],"['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes...","'전기', '드라마', '역",제 2 차 세계 대전 당시 독일 점령 폴란드에서 산업 주의자 Oskar Schind...
15991,Berkeley Cole,Out of Africa (1985),6/0,INFJ,1w9,movies,https://static1.personality-database.com/profi...,210,out of africa,1959.0,Out of Africa,"['Biography', 'Drama', 'Romance']","['In 20th-century colonial Kenya, a Danish bar...",['Sydney Pollack'],"['Meryl Streep', 'Robert Redford', 'Klaus Mari...","'전기', '드라마', '로맨",20 세기 식민지 케냐에서 덴마크의 남작/농장 소유자는 자유로운 큰 빅 게임 헌터와...
15992,The Girl,A Girl Walks Home Alone at Night (2014),6/0,INFJ,4w5,movies,https://static1.personality-database.com/profi...,210,a girl walks home alone at night,118880.0,NaN,NaN,NaN,NaN,NaN,장르 정보 없음,줄거리 정보 없음
15993,Urzah,The Dark Crystal (1982),6/0,INFJ,9w1,movies,https://static1.personality-database.com/profi...,210,the dark crystal,91077.0,The Dark Crystal,"['Adventure', 'Family', 'Fantasy']",NaN,"['Jim Henson', 'Frank Oz']","['Jim Henson', 'Kathryn Mullen', 'Frank Oz', '...","'Adventure', 'Family', 'Fantas",줄거리 정보 없음
15994,Dr. Leonora Orantes,Contagion (2011),6/0,INFJ,9w1,movies,https://static1.personality-database.com/profi...,210,contagion,89470.0,Contagion,"['Drama', 'Thriller']","['Healthcare professionals, government officia...",['Steven Soderbergh'],"['Gwyneth Paltrow', 'Tien You Chui', 'Josie Ho...","'드라마', '스릴","의료 전문가, 공무원 및 일상적인 사람들은 CDC가 치료법을 찾기 위해 일할 때 전..."

In [36]:
ko_3229_merge_df.to_csv('/opt/ml/input/final_project/Data/Crawling/3229_plus_side_info_plus_korean_genre_and_plot.csv')