In [1]:
import pandas as pd

In [6]:
cdf = pd.read_pickle('../../Utils/Pickle/230203_character_movie_merge.pickle')
mdf = pd.read_pickle('../../Utils/Pickle/230130_Popular_movie_1192_cwj.pickle')

cinfo2 = pd.read_pickle('../../Utils/Pickle/processed_ko_cha_info.pickle')

In [13]:
!ls ../../Utils/Pickle/*link*

../../Utils/Pickle/230131_watch_link_4679_rows.pickle
../../Utils/Pickle/watch_link_3229movie_4462_rows.pickle

In [14]:
link = pd.read_pickle('../../Utils/Pickle/230131_watch_link_4679_rows.pickle')

In [8]:
cdf2 = cdf.merge(cinfo2, on='CharacterId')
cdf2[:2]

,CharacterId,Character,vote,MBTI,Enneagram,movieId,contents_year,Contents,ko_title,rating,npop,img_src,name,desc
0,13078,Bruno Madrigal,7300,ISFJ,6w5,300005,2021,Encanto (2021),엔칸토: 마법의 세계,3.5,30000,https://static1.personality-database.com/profi...,브루노 마드리갈,"브루노는 엔카토 마을의 소년으로, 상상력과 독창적인 생각으로 마을 사람들의 인생을 ..."
1,19465,Tyler Durden,6900,ESTP,8w7,2959,1999,Fight Club (1999),파이트 클럽,4.1,340000,https://static1.personality-database.com/profi...,타일러 더든,타일러 더든은 피터의 내면의 이상한 모습이다. 피터는 타일러를 자신의 내면의 악마라...

In [40]:
cdf_result = cdf2[['MBTI','vote','CharacterId','name','desc','img_src','movieId']]
cdf_result[:5]

,MBTI,vote,CharacterId,name,desc,img_src,movieId
0,ISFJ,7300,13078,브루노 마드리갈,"브루노는 엔카토 마을의 소년으로, 상상력과 독창적인 생각으로 마을 사람들의 인생을 ...",https://static1.personality-database.com/profi...,300005
1,ESTP,6900,19465,타일러 더든,타일러 더든은 피터의 내면의 이상한 모습이다. 피터는 타일러를 자신의 내면의 악마라...,https://static1.personality-database.com/profi...,2959
2,INFJ,6200,22947,엘사,"엘사는 디즈니 애니메이션 영화 '겨울왕국'의 주인공으로, 바다에서 나온 왕국 아렌델...",https://static1.personality-database.com/profi...,75395
3,INFJ,6000,22948,로키 라프소슨,"로키는 아스가르드의 왕자로, 스노우 바루스의 왕자이자 아이언 맨과 헐크의 연결고리이...",https://static1.personality-database.com/profi...,300932
4,ENTJ,6000,8133,패트릭 베이텀,패트릭 베이텀은 뉴욕의 중산층 연금술사로 일하는 남자이다. 그는 외모는 완벽하고 몸...,https://static1.personality-database.com/profi...,3535

In [19]:
mdf_result = mdf[['movieId','ko_title','ko_plot']]
mdf_result[:5]

   movieId   ko_title                                            ko_plot
0    73141        모아나  바다가 선택한 소녀, 모아나. 저주에 걸린 모투누이 섬을 구하기 위해 머나먼 항해를...
1   122470    인사이드 아웃  모든 사람의 머릿속에 존재하는 감정 컨트롤 본부. 그곳에서 불철주야 열심히 일하는 ...
2   152081       주토피아  교양 있고 세련된 라이프 스타일을 주도하는 도시 주토피아. 이 곳을 단숨에 혼란에 ...
3     4447    금발이 너무해  부유한 집안 출신에 금발과 제법 큰 가슴을 지닌 여학생 클럽 회장 엘 우즈. 세상 ...
4     1246  죽은 시인의 사회                                      “오 캡틴, 나의 캡틴”

In [20]:
link_result = link[['movieId','platform','link']]
link_result[:5]

   movieId platform                                               link
0    73141     디즈니+  https://disneyplus.bn5x.net/c/3581330/1182069/...
1   122470     디즈니+  https://disneyplus.bn5x.net/c/3581330/1182069/...
2   152081     디즈니+  https://disneyplus.bn5x.net/c/3581330/1182069/...
3     4447  no_link                                            no_link
4     1246     디즈니+  https://disneyplus.bn5x.net/c/3581330/1182069/...

In [41]:
cdf_result.sort_values(['MBTI','vote'],ascending=(1,0)).to_csv('230211_for_abnormal_process_character_2867.csv',index=False)
cdf_result.sort_values(['MBTI','vote'],ascending=(1,0))

,MBTI,vote,CharacterId,name,desc,img_src,movieId
27,ENFJ,2700,0,모아나 와이알리키,"모아나는 태평양의 섬 마셰이의 왕자로, 자신의 섬을 위해 여행을 떠나는 주인공이다....",https://static1.personality-database.com/profi...,73141
30,ENFJ,2500,2,조이,"조이는 라이언의 마음 속에 있는 기쁨을 나타내는 캐릭터로, 기쁨과 에너지가 넘치는 ...",https://static1.personality-database.com/profi...,122470
38,ENFJ,2300,3,주디 호프스,주디 호프스는 종족 차별을 극복하기 위해 도전하는 열정적인 토끼 주민입니다. 주디는...,https://static1.personality-database.com/profi...,152081
54,ENFJ,1900,4,엘 모어즈,"엘 모어즈는 미국 버클리 대학교의 소셜학부 학생으로, 명문 로스앤젤레스 변호사가 되...",https://static1.personality-database.com/profi...,4447
66,ENFJ,1700,5,닐 페리,"닐 페리는 뉴에이지 스쿨의 학생으로, 자신의 열정과 상상력을 통해 자신의 방향을 찾...",https://static1.personality-database.com/profi...,1246
...,...,...,...,...,...,...,...
2835,ISTP,10,22547,휘슬러,휘슬러는 블레이드의 전사이자 동료이다. 그는 블레이드가 마법사 메디슨과의 전투를 승...,https://static1.personality-database.com/profi...,2167
2836,ISTP,10,22587,찰리 크로커,찰리 크로커는 영국의 장악하는 도둑이다. 그는 아이디어로 매력적인 도둑질 작업을 수...,https://static1.personality-database.com/profi...,6378
2837,ISTP,10,22589,샘 벨,"샘 벨은 우주에서 일하는 엔지니어로, 천체관측 장비를 점검하고 위험한 상황을 피하기...",https://static1.personality-database.com/profi...,68237
2839,ISTP,10,22624,잭 샤델슈타인,잭 샤델슈타인은 가족과 친구들과의 관계를 바라보는 다른 관점을 가진 남자입니다. 그...,https://static1.personality-database.com/profi...,90890
2840,ISTP,10,22608,안젤리카,안젤리카는 브라더스 그림의 주인공이다. 그녀는 자신의 동생인 잭과 함께 요정들과 마...,https://static1.personality-database.com/profi...,1037

In [35]:
set(cdf_result.sort_values(['MBTI','vote'],ascending=(1,0)).MBTI)

{'ENFJ',
 'ENFP',
 'ENTJ',
 'ENTP',
 'ESFJ',
 'ESFP',
 'ESTJ',
 'ESTP',
 'INFJ',
 'INFP',
 'INTJ',
 'INTP',
 'ISFJ',
 'ISFP',
 'ISTJ',
 'ISTP'}

In [32]:
mdf_result.sort_values('movieId').to_csv('230211_for_abnormal_process_movie_1192.csv',index=False)
mdf_result.sort_values('movieId')

,movieId,ko_title,ko_plot
12,1,토이 스토리 4,우리의 여행은 아직 끝나지 않았다.
118,2,쥬만지: 넥스트 레벨,"진화된 게임, 주어진 목숨은 3개!"
721,48,포카혼타스,1607년 젊은 미남 선장 존 스미스는 황금에 눈 먼 총독 랫클리프와 신대륙을 향해...
901,50,유주얼 서스펙트,"산 페드로 부두에서 27명이 사망하고 9,100만달러가 증발하는 유혈극이 벌어진다...."
376,73,레미제라블,빵 한 조각을 훔친 죄로 19년의 감옥살이를 한 장발장(휴 잭맨). 전과자라는 이유...
...,...,...,...
1187,300997,스파이더맨: 홈커밍,‘시빌 워’ 당시 ‘토니 스타크’(로버트 다우니 주니어)에게 발탁되어 대단한 활약을...
1188,300998,왓치맨,이제 히어로들의 반란이 시작된다!
1189,300999,판타스틱 4,천재적인 두뇌의 소유자 리드(마일즈 텔러). 저명한 과학자 스톰 박사의 눈에 띄어 ...
1190,301010,데어데블,“2003년 최고의 슈퍼 히어로가 온다!”
1191,301014,배트맨 대 슈퍼맨: 저스티스의 시작,모든 대결에는 이유가 있다!

In [33]:
link_result.sort_values(['movieId','platform']).to_csv('230211_for_abnormal_process_link_4679.csv',index=False)
link_result.sort_values(['movieId','platform'])

      movieId platform                                               link
14          1     디즈니+  https://disneyplus.bn5x.net/c/3581330/1182069/...
253         2       왓챠  https://redirect.watcha.com/galaxy/aHR0cHM6Ly9...
254         2       티빙  https://redirect.watcha.com/galaxy/aHR0cHM6Ly9...
3180        4  no_link                                            no_link
1570        6     디즈니+  https://disneyplus.bn5x.net/c/3581330/1182069/...
...       ...      ...                                                ...
209    301010     디즈니+  https://disneyplus.bn5x.net/c/3581330/1182069/...
210    301010       티빙  https://redirect.watcha.com/galaxy/aHR0cHM6Ly9...
212    301014     넷플릭스  https://redirect.watcha.com/galaxy/aHR0cHM6Ly9...
211    301014       왓챠  https://redirect.watcha.com/galaxy/aHR0cHM6Ly9...
213    301014      웨이브  https://redirect.watcha.com/galaxy/aHR0cHM6Ly9...

[4679 rows x 3 columns]

In [37]:
cdf_result[cdf_result.name.str.contains('Abne')]

Empty DataFrame
Columns: [MBTI, vote, CharacterId, name, desc, img_src]
Index: []

In [ ]:
잘못 될 수 있는 데이터
    캐릭터가 이상한 경우 -> 캐릭터 삭제
    ex) Abnegation - 캐릭터가 아니라 단체
    캐릭터와 영화 잘못 연결 -> 영화를 제대로 연결시키고, 영화 정보 수정
    ex) 스플릿, 반지의 제왕 두개의 탑, 7번방의 기적
    영화와 포스터가 잘못 연결된 경우 -> 포스터 수정
    영화 제목, 영화 설명, 링크
    감상가능한 곳 링크 이상한 경우

In [4]:
mdf.columns

Index(['Contents', 'ko_title', 'contents_year', 'country', 'ko_genre',
       'ko_plot', 'rating', 'npop', 'genres', 'plot', 'directors', 'actors',
       'movieId'],
      dtype='object')